### ISSUE TITLE
Ace-editor style cannot pierce through the shadow DOM.

### ISSUE THREAD

**Issue by arodic** [Juicy/juicy-ace-editor#4]
Once ace editor is created, the stylesheets are generated by javascript and added to the <head> section of the document. However, the CSS selectors are not able to pierce through the shadow DOM barrier. As the result, it is impossible to use juicy-ace-editor in shadow DOM.

Here is an example of a CSS selector generated by ace:
``` css
.ace_editor {position: relative;}
```

To support the shadow DOM use, all selectors would need to change to something like this:

``` css
html /deep/ .ace_editor {position: relative;}
```

Alternatively, the ace-editor style should be encapsulated inside the juicy-ace-editor component and not leak outside.
